name: auth_bloc
description: "A new Flutter project."

publish_to: "none" 

version: 1.5.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.1
  cached_network_image: any
  cupertino_icons: ^1.0.6
  firebase_auth: any
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_offline: ^3.0.1
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  rive: ^0.13.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/svgs/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700