name: auth_bloc
description: "A new Flutter project."

publish_to: "none" 

version: 1.5.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.2.1
  cached_network_image: any
  cupertino_icons: ^1.0.8
  firebase_auth: any
  firebase_core: ^3.12.1
  flutter_bloc: ^9.1.0
  flutter_offline: ^4.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  google_sign_in: ^6.3.0
  rive: ^0.13.20

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/svgs/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700